import { ReviewCardItemsType } from "../Types";

export const ReviewCardItem: ReviewCardItemsType[] = [
    {
        category: "monthly", 
        header: "Free",
        title: "So you can see how incredible our tool is.",
        price: 0,
        description: "Free for ever",
        Trial: "No credit card needed",
        features: [
            "A cool feature",
            "A basic feature",
            "A top feature with limitations",
            "An incredible feature so useful",
            "A top feature",
        ],
        specialComment: false,
    },
    {
        category: "monthly", 
        header: "Starter",
        title: "So you can see how incredible our tool is. ",
        price: 19,
        description: "Billed monthly",
        Trial: "7 days free trial no credit card needed",
        features: [
            "A cool feature",
            "A basic feature",
            "A top feature with limitations",
            "An incredible feature so useful",
            "A top feature",
        ],
        specialComment: true,
    },
    {
        category: "monthly", 
        header: "Pro",
        title: "So you can see how incredible our tool is.",
        price: 49,
        description: "Billed monthly",
        Trial: "7 days free trial no credit card needed",
        features: [
            "A cool feature",
            "A basic feature",
            "A top feature with limitations",
            "An incredible feature so useful",
            "A premium feature",
            "You need this feature",
        ],
        specialComment: false,
    },
    {
        category: "annually", 
        header: "Free",
        title: "So you can see how incredible our tool is.",
        price: 0,
        description: "Free for ever",
        Trial: "No credit card needed",
        features: [
            "A cool feature",
            "A basic feature",
            "A top feature with limitations",
            "An incredible feature so useful",
            "A top feature",
        ],
        specialComment: false,
    },
    {
        category: "annually", 
        header: "Starter",
        title: "So you can see how incredible our tool is. ",
        price: 15,
        description: "Billed $180 yearly",
        Trial: "7 days free trial no credit card needed",
        features: [
            "A cool feature",
            "A basic feature",
            "A top feature with limitations",
            "An incredible feature so useful",
            "A top feature",
        ],
        specialComment: true,
    },
    {
        category: "annually", 
        header: "Pro",
        title: "So you can see how incredible our tool is.",
        price: 45,
        description: "Billed $540 yearly",
        Trial: "7 days free trial no credit card needed",
        features: [
            "A cool feature",
            "A basic feature",
            "A top feature with limitations",
            "An incredible feature so useful",
            "A premium feature",
            "You need this feature",
        ],
        specialComment: false,
    },
];
